name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "bot@github.com"
      - run: git config --global user.name "GitHub Bot"
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run release
